# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
  postgres:
    image: postgres:9.6.8-alpine
    environment:
      POSTGRES_DB: npr
      POSTGRES_USER: npr-db-usr
      POSTGRES_PASSWORD: npr-db-password
      
